### ISSUE TITLE
Not finding issue

### ISSUE THREAD

**Issue by zahroc** [Pewsplosions/Comicalibre#1]
Maybe I am daft but no matter how I configured per your instructions, it never found the issue.
The URL to the issue is https://comicvine.gamespot.com/battlestar-galactica-1-volume-1/4000-429066/

Would you be so kind as to give an example for each search on using this actual comic?

**Comment by pewsplosions** [comment]
Try this as the issue name:

`Battlestar Galactica --- v68412 n001`

The URL you have looks like an issue page, so that ID is the issue ID. This is the volume page: [https://comicvine.gamespot.com/battlestar-galactica/4050-68412/](https://comicvine.gamespot.com/battlestar-galactica/4050-68412/)

I designed it to use the volume ID and issue number instead of individual issue IDs so you can do large amounts of issues in a single volume without having to get all the individual issue IDs from comic vine. Just have to get the volume ID, in this case 68412. Rename all the comics based on that + the issue number. And it should just get it all for every issue at once.

Hope this helps!

If you still have problems, feel free to send me what options in the plugin you are choosing and what the data looks like in Calibre before running. I'll see if I can replicate it.

**Comment by zahroc** [comment]
Getting things to work. Thanks for the solution. One item I am seeing though, the actual title meta data is not updating to the "Name" from Comic Vine. Am I missing something?

**Comment by pewsplosions** [comment]
That is actually by design. I wrote it that way so I can make the 'book title' what I wanted.

In the above example, if you wanted it to be anything but Battlestar Galactica,  you'd just change that part of the file's title.

I can't remember if I built in a way to get the title from comic vine. You may try importing. Then doing it again, but this time use the 3rd option. The one that uses the specific comic vine IDs that were imported by the first option. I remember the purpose of this was to refresh the meta data. I cannot remember if this option actually updates the title though.
